### ISSUE TITLE
Item Duping With Drying Racks

### ISSUE THREAD

**Issue by TheLimePixel** [CyclopsMC/StructuredCrafting#16]
#### Issue type:
:bug:

#### Expected behaviour:
 Items put on drying racks behind the Structured Crafter are used up.

#### Actual behaviour:
 Items placed on Tinker's Construct Drying Racks don't get used up, making it so you can in theory duplicate items.

#### Versions:
 Every 1.12.2 version of the mod.

**Comment by Bockiii** [comment]
Found another dupe bug having to do with the drying rack thats a bit weirder:

Steps to reproduce:
1. Put crafter down so that 3 wood slabs are behind it (imagine being on a sky island made of slabs and put it down). Put a Chest in front of it.
2. Activate with lever, crafter will produce one drying rack (and consume the slabs) and stop
3. Place one chest behind the crafter and another chest above that chest. Place something that has a one-to-many recipe in the chest behind the crafter (like log/plank, iron ingot/iron nugget, coal/mini coal).
4. Activate the crafter.

It will consume the lower chest and the item in it, creating mini chests and the nuggets for example but will keep creating the nuggets forever, thus duping everything with a 1-X crafting recipe. I didnt test further if more combinations are possible.

Found in Modern Skyblock 2, 2.6.2.4

**Comment by TheLimePixel** [comment]
I'm pretty sure that that was fixed in the next version of the pack/next version of the mod.
